name: my_app
description: A new Flutter project.

publish_to: "none" 

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_sign_in: ^5.4.2
  firebase_core: ^1.23.0
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.5.0
  sqflite: ^2.1.0+1
  path: ^1.8.2
  shared_preferences: ^2.0.15
  firebase_storage: ^10.3.11
  firebase_crashlytics: ^2.9.0
  flutter_svg: ^1.1.5
  status_change: ^2.0.0
  flutter_timeline: ^0.3.0
  im_stepper: ^1.0.1+1
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  
  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/menu_icons/
    - assets/fonts/
    - assets/category_icons/

  
  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf
  
