name: my_app
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.1
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  sqflite: ^2.1.0+1
  path: ^1.8.2
  shared_preferences: ^2.0.15
  firebase_storage: ^11.0.4
  firebase_crashlytics: ^3.0.4
  flutter_svg: ^1.1.5
  status_change: ^2.0.0
  flutter_timeline: ^0.3.0
  im_stepper: ^1.0.1+1
  sliding_up_panel: ^2.0.0+1
  carousel_slider: ^4.1.1
  flutter_launcher_icons: ^0.10.0
  photo_view: ^0.14.0
  flutter_native_splash: ^2.2.14
flutter_native_splash:
  background_image: "assets/icons/splash_image.png"

flutter_icons:
android: true
ios: true
remove_alpha_ios: true
image_path: "assets/icons/playstore.png"

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/menu_icons/
    - assets/fonts/
    - assets/category_icons/

  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf
